version: '3'
services:
  web:
    build: .
    ports:
     - "49160:8080"
    volumes:
     - ./server:/usr/src/app
    depends_on:
      - "db"
#    command: [ "./wait-for-postgres.sh &&  npm run dev"] 
#&& sequelize db:migrate && sequelize db:seed:all 
    
#    command: [ "./wait-for-postgres.sh",  "db" , "npm","run","dev"]
     
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=practicedocker     
#    volumes:
#      - ./init.sql:/docker-entrypoint-initdb.d/init.sql      